"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

from io import BytesIO
import struct

class high_command_lcmt(object):
    __slots__ = ["vx", "vy", "vyaw", "timestamp_us", "id", "robot_id"]

    __typenames__ = ["double", "double", "double", "int64_t", "int64_t", "int64_t"]

    __dimensions__ = [None, None, None, None, None, None]

    def __init__(self):
        self.vx = 0.0
        self.vy = 0.0
        self.vyaw = 0.0
        self.timestamp_us = 0
        self.id = 0
        self.robot_id = 0

    def encode(self):
        buf = BytesIO()
        buf.write(high_command_lcmt._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">dddqqq", self.vx, self.vy, self.vyaw, self.timestamp_us, self.id, self.robot_id))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != high_command_lcmt._get_packed_fingerprint():
            raise ValueError("Decode error")
        return high_command_lcmt._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = high_command_lcmt()
        self.vx, self.vy, self.vyaw, self.timestamp_us, self.id, self.robot_id = struct.unpack(">dddqqq", buf.read(48))
        return self
    _decode_one = staticmethod(_decode_one)

    def _get_hash_recursive(parents):
        if high_command_lcmt in parents: return 0
        tmphash = (0xfe52b010b7eda7a3) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if high_command_lcmt._packed_fingerprint is None:
            high_command_lcmt._packed_fingerprint = struct.pack(">Q", high_command_lcmt._get_hash_recursive([]))
        return high_command_lcmt._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", high_command_lcmt._get_packed_fingerprint())[0]

